version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:${DB_PORT}
  backend:
    restart: always
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4001:4001"
  frontend:
    depends_on:
      - db
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
  