version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
  frontend:
    depends_on:
      - db
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
  